baseURL = 'https://ouisync.net/'
languageCode = 'en'
title = 'My New Hugo Site'
copyright = 'Everything is mine'
defaultContentLanguage = 'en'
[languages]
    [languages.en]
        title = 'Ouisync'
        languageName = 'English'
        contentDir = 'content/en'
        languageDirection = 'ltr'
        weight = 1
    [languages.fr]
        title = 'Ouisync (fr)'
        languageName = 'French'
        languageDirection = 'rtl'
        contentDir = 'content/fr'
        weight = 2

# So we can use normal HTML inside of .md files     
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

