baseURL = 'https://willow446.github.io/ouisync-test-repo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
copyright = 'Everything is mine'
defaultContentLanguage = 'en-us'
[languages]
    [languages.en-us]
        title = 'Ouisync'
        languageName = 'English'
        weight = 1
    [languages.fr]
        title = 'Ouisync (fr)'
        languageName = 'French'
        weight = 2
