baseURL = 'https://ouisync.net/'
languageCode = 'en'
title = 'My New Hugo Site'
copyright = 'Everything is mine'
defaultContentLanguage = 'en'
[languages]
    [languages.en]
        title = 'Ouisync'
        languageName = 'English'
        contentDir = 'content/en'
        languageDirection = 'ltr'
        weight = 1
    [languages.fr]
        disabled = true
        title = 'Ouisync (fr)'
        languageDirection = 'ltr'
        languageName = 'French'
        contentDir = 'content/fr'
        weight = 2
    [languages.es]
        disabled = true
        title = 'Ouisync (es)'
        languageDirection = 'ltr'
        languageName = 'Spanish'
        contentDir = 'content/es'
        weight = 2
    [languages.fa]
        title = 'Ouisync (fa)'
        languageDirection = 'rtl'
        languageName = 'Persian'
        contentDir = 'content/fa'
        weight = 2
    [languages.my]
        disabled = true
        title = 'Ouisync (my)'
        languageDirection = 'ltr'
        languageName = 'Burmese'
        contentDir = 'content/my'
        weight = 2
    [languages.ru]
        title = 'Ouisync (ru)'
        languageDirection = 'ltr'
        languageName = 'Russian'
        contentDir = 'content/ru'
        weight = 2
    [languages.uk]
        disabled = true
        title = 'Ouisync (uk)'
        languageDirection = 'ltr'
        languageName = 'Ukrainian'
        contentDir = 'content/uk'
        weight = 2
        

# So we can use normal HTML inside of .md files     
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

