baseURL = 'https://willow446.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
copyright = 'Everything is mine'
defaultContentLanguage = 'en-us'
[languages]
    [languages.en-us]
        title = 'Ouisync'
        languageName = 'English'
        contentDir = 'content/en-us'
        weight = 1
    [languages.fr]
        title = 'Ouisync (fr)'
        languageName = 'French'
        contentDir = 'content/fr'
        weight = 2

# So we can use normal HTML inside of .md files     
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

