baseURL = 'https://ouisync.net/'
languageCode = 'en'
title = 'My New Hugo Site'
copyright = 'Everything is mine'
defaultContentLanguage = 'en'
[languages]
    [languages.en]
        title = 'Ouisync'
        languageName = 'English'
        contentDir = 'content/en'
        languageDirection = 'ltr'
        weight = 1
    [languages.fr]
        disabled = false
        title = 'Ouisync (fr)'
        languageDirection = 'ltr'
        languageName = 'French'
        contentDir = 'content/fr'
        weight = 2
    [languages.es]
        disabled = false
        title = 'Ouisync (es)'
        languageDirection = 'ltr'
        languageName = 'Spanish'
        contentDir = 'content/es'
        weight = 2
    [languages.fa]
        title = 'Ouisync (fa)'
        languageDirection = 'rtl'
        languageName = 'Persian'
        contentDir = 'content/fa'
        weight = 2
    [languages.my]
        disabled = true
        title = 'Ouisync (my)'
        languageDirection = 'ltr'
        languageName = 'Burmese'
        contentDir = 'content/my'
        weight = 2
    [languages.ru]
        title = 'Ouisync (ru)'
        languageDirection = 'ltr'
        languageName = 'Russian'
        contentDir = 'content/ru'
        weight = 2
    [languages.uk]
        disabled = true
        title = 'Ouisync (uk)'
        languageDirection = 'ltr'
        languageName = 'Ukrainian'
        contentDir = 'content/uk'
        weight = 2

# Configure mounts for fallback translation pages
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

[[module.mounts]]
source = 'content/es'
target = 'content'
lang = 'es'

[[module.mounts]]
source = 'content/fa'
target = 'content'
lang = 'fa'

[[module.mounts]]
source = 'content/fr'
target = 'content'
lang = 'fr'

[[module.mounts]]
source = 'content/my'
target = 'content'
lang = 'my'

[[module.mounts]]
source = 'content/ru'
target = 'content'
lang = 'ru'

[[module.mounts]]
source = 'content/uk'
target = 'content'
lang = 'uk'

# This fills in the gaps in translated content with EN content.
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'es'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'fa'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'fr'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'my'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'ru'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'uk'

        

# So we can use normal HTML inside of .md files     
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

